/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-13 14:02:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addPatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1626071547228L));
    _jspx_dependants.put("/menu/top.jsp", Long.valueOf(1624884232400L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("  	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("        <link rel=\"icon\" href=\"../../../../favicon.ico\">\n");
      out.write("        \n");
      out.write("        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\n");
      out.write("        <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\n");
      out.write("        <!-- Bootstrap core CSS -->\n");
      out.write("        \n");
      out.write("         \n");
      out.write("         <link rel=\"stylesheet\" href=\"dist/css/adminlte.min.css\">  \n");
      out.write("        <script src=\"dist/js/adminlte.min.js\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"hold-transition sidebar-mini\" style=\"size: 75%;\">\n");
      out.write("        <div class=\"wrapper\">\n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a> \n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item d-none d-sm-inline-block\">\n");
      out.write("                    <a href=\"home.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("            <div style=\"text-align: center; font-weight: 900;\" class=\"title\">\n");
      out.write("                PATIENT Retention Program\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </nav>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>menu</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\n");
      out.write("            <div class=\"sidebar\">\n");
      out.write("                <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\n");
      out.write("                    <div class=\"info\">\n");
      out.write("                        <a href=\"#\" class=\"d-block\" style=\"font-size: 200%;\">PATIENT REPORT</a>\n");
      out.write("                        <b style=\"color:white;\">\n");
      out.write("                            ");
if(session.getAttribute("fullname")!=null){
                                String name=session.getAttribute("fullname").toString();
                                out.println(name); 
                            
      out.write(" \n");
      out.write("                            ");
}
      out.write("\n");
      out.write("                        </b>\n");
      out.write("                        <br>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                        <nav class=\"mt-2\">\n");
      out.write("                            <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\n");
      out.write("                                ");
 if(session.getAttribute("fullname")!=null){
      out.write("\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"addPatient.jsp\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Add Patients\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"ManagePatients.jsp\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Manage Patients\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                 <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"#\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Reports\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                ");
}else{
                                    String nextpage="index.jsp";
                                    response.sendRedirect(nextpage);
                                    
                                }
                                
      out.write("\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                <a href=\"logout\" class=\"nav-link\">\n");
      out.write("                                  <i class=\"nav-icon fas fa-lock\"></i>\n");
      out.write("                                  <p>\n");
      out.write("                                   Logout\n");
      out.write("                                  </p>\n");
      out.write("                                </a>\n");
      out.write("                             </li>\n");
      out.write("                                \n");
      out.write("                            </ul>\n");
      out.write("                            \n");
      out.write("                        </nav>\n");
      out.write("            </div>\n");
      out.write("        </aside>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("            <div class=\"content-wrapper\">\n");
      out.write("                <main role=\"main\" class=\"container\">\n");
      out.write("            <h1 class=\"mt-5\">Register New Patients</h1>\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <div class=\"col-4\">\n");
      out.write("                    <img src=\"img/user1.png\"class=\"img-fluid\"/>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                <div class=\"col-6\">\n");
      out.write("                    <form action=\"addpatients\" method=\"post\">\n");
      out.write("				  <div class=\"mb-3\">\n");
      out.write("				    <label for=\"firstname\" class=\"form-label\">First Name <b style=\"color:red;\"> *</b>F</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"fname\" placeholder=\"First Name\" required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("\n");
      out.write("				  <div class=\"mb-3\">\n");
      out.write("				    <label for=\"middlenaame\" class=\"form-label\">Middle Name<b style=\"color:red;\"> *</b>MN</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"mname\" placeholder=\"Middle Name\" required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("                                 <div class=\"mb-3\">\n");
      out.write("				    <label for=\"lastname\" class=\"form-label\">Last Name<b style=\"color:red;\"> *</b>L</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"lname\" placeholder=\"Last Name\" required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("				   <div class=\"mb-3\">\n");
      out.write("				    <label for=\"patientnumber\" class=\"form-label\">Patient Number<b style=\"color:red;\"> *</b>PN</label>\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"pnumber\" placeholder=\"Patient Number\" required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"mb-3\">\n");
      out.write("				    <label for=\"birthday\" class=\"form-label\">DOB<b style=\"color:red;\"> *</b>DOB</label>\n");
      out.write("				    <input type=\"date\" class=\"form-control\" name=\"dob\" required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("				  <div class=\"mb-3\">\n");
      out.write("				    <label for=\"maritalstatus\" class=\"form-label\">Marital Status <b style=\"color:red;\"> *</b>MS</label>\n");
      out.write("				    <select name=\"m_status\">\n");
      out.write("                                        <option value=\"1\">Single</option>\n");
      out.write("                                        <option value=\"2\">Married</option>\n");
      out.write("                                        <option value=\"3\">Widowed</option>\n");
      out.write("                                        <option value=\"4\">Divorced</option>\n");
      out.write("                                    </select>\n");
      out.write("				  </div>\n");
      out.write("                        \n");
      out.write("				 <div class=\"mb-3\">\n");
      out.write("				     <p>\n");
      out.write("                                    Patient Status <b style=\"color:red;\"> *</b>PS\n");
      out.write("                                    <input type=\"radio\" name=\"p_status\" value=\"1\">Active\n");
      out.write("                                    <input type=\"radio\" name=\"p_status\" value=\"2\">is_dead\n");
      out.write("                                    </p>\n");
      out.write("                               \n");
      out.write("				  </div>\n");
      out.write("                                    <div class=\"mb-3\">\n");
      out.write("                                        <p>\n");
      out.write("                                    Gender <b style=\"color:red;\"> *</b>G\n");
      out.write("                                    <input type=\"radio\" name=\"gender\" value=\"Male\">Male\n");
      out.write("                                    <input type=\"radio\" name=\"gender\" value=\"Female\">Female\n");
      out.write("                                    </p>\n");
      out.write("                                    </div>\n");
      out.write("                                 <div class=\"mb-3\">\n");
      out.write("				    <label for=\"nationalid\" class=\"form-label\">National Id<b style=\"color:red;\"> *</b>id</label>\n");
      out.write("				    <input type=\"text\" class=\"form-control\"minlength=\"10\" maxlength=\"10\" id=\"nid\" name=\"nid\" maxlength=\"10\" placeholder=\"National Id\" onkeypress='return numbers(event)'>\n");
      out.write("				  </div>\n");
      out.write("                                    \n");
      out.write("				 \n");
      out.write("				  <div class=\"mb-3\">\n");
      out.write("				    <label for=\"phonenumber\" class=\"form-label\">Phone Number<b style=\"color:red;\"> *</b>P</label>\n");
      out.write("				    <input type=\"text\" class=\"form-control\"minlength=\"10\" maxlength=\"10\" id=\"phone\" name=\"phone\" maxlength=\"10\" placeholder=\"Phone Number\" onkeypress='return numbers(event)' required=\"true\">\n");
      out.write("				  </div>\n");
      out.write("				 \n");
      out.write("				  <button type=\"submit\" name=\"save\" class=\"btn btn-primary\">Save</button>\n");
      out.write("		</form>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </main>\n");
      out.write("                \n");
      out.write("            </div>\n");
      out.write("        \n");
      out.write("        ");

                     try{
                         if(session.getAttribute("message")!=null){
                             String mess =session.getAttribute("message").toString();
                             out.print(mess);
                         }else{
                             session.removeAttribute("message");
                         }
                         
                     }catch(Exception e){
                         out.print(e.getMessage());
                         
                     }
                 
      out.write("\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("         \n");
      out.write("    </body>\n");
      out.write("  <script type=\"text/javascript\" language=\"en\">\n");
      out.write("   function numbers(evt){\n");
      out.write("var charCode=(evt.which) ? evt.which : event.keyCode\n");
      out.write("if(charCode > 31 && (charCode < 48 || charCode>57))\n");
      out.write("return false;\n");
      out.write("return true;\n");
      out.write("}\n");
      out.write("//-->\n");
      out.write("</script>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
