/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.66
 * Generated at: 2021-07-15 14:00:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;

public final class ManagePatients_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/menu/menu.jsp", Long.valueOf(1626071547228L));
    _jspx_dependants.put("/menu/top.jsp", Long.valueOf(1624884232400L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <script src=\"http://code.jquery.com/jquery-1.11.3.min.js\"></script>\n");
      out.write("         <script src=\"https://code.jquery.com/ui/1.11.3/jquery-ui.js\"></script>\n");
      out.write("         \n");
      out.write("         <script type=\"text/javascript\" charset=\"utf8\" src=\"https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js\"></script>\n");
      out.write("         <link rel=\"stylesheet\" type=\"text/css\" href=\"https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css\">\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("	<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\n");
      out.write("       <link rel=\"stylesheet\" href=\"plugins/datatables-bs4/css/dataTables.bootstrap4.min.css\">\n");
      out.write("       <link rel=\"stylesheet\" href=\"plugins/datatables-responsive/css/responsive.bootstrap4.min.css\">\n");
      out.write("  \n");
      out.write("        <link rel=\"stylesheet\" href=\"dist/css/adminlte.min.css\">  \n");
      out.write("        <script src=\"dist/js/adminlte.min.js\"></script>\n");
      out.write("       <script src=\"plugins/datatables-bs4/js/dataTables.bootstrap4.min.js\"></script>\n");
      out.write("       <script src=\"plugins/datatables-responsive/js/dataTables.responsive.min.js\"></script>\n");
      out.write("       <script src=\"plugins/datatables-responsive/js/responsive.bootstrap4.min.js\"></script>\n");
      out.write("       \n");
      out.write("\n");
      out.write("        \n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"hold-transition sidebar-mini\" style=\"size: 75%;\">\n");
      out.write("      <div class=\"wrapper\">\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav class=\"main-header navbar navbar-expand navbar-white navbar-light\">\n");
      out.write("            <ul class=\"navbar-nav\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" data-widget=\"pushmenu\" href=\"#\" role=\"button\"><i class=\"fas fa-bars\"></i></a> \n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item d-none d-sm-inline-block\">\n");
      out.write("                    <a href=\"home.jsp\" class=\"nav-link\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                \n");
      out.write("            </ul>\n");
      out.write("            <div style=\"text-align: center; font-weight: 900;\" class=\"title\">\n");
      out.write("                PATIENT Retention Program\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </nav>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <title>menu</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <aside class=\"main-sidebar sidebar-dark-primary elevation-4\">\n");
      out.write("            <div class=\"sidebar\">\n");
      out.write("                <div class=\"user-panel mt-3 pb-3 mb-3 d-flex\">\n");
      out.write("                    <div class=\"info\">\n");
      out.write("                        <a href=\"#\" class=\"d-block\" style=\"font-size: 200%;\">PATIENT REPORT</a>\n");
      out.write("                        <b style=\"color:white;\">\n");
      out.write("                            ");
if(session.getAttribute("fullname")!=null){
                                String name=session.getAttribute("fullname").toString();
                                out.println(name); 
                            
      out.write(" \n");
      out.write("                            ");
}
      out.write("\n");
      out.write("                        </b>\n");
      out.write("                        <br>\n");
      out.write("                        \n");
      out.write("                    </div>\n");
      out.write("                    \n");
      out.write("                </div>\n");
      out.write("                        <nav class=\"mt-2\">\n");
      out.write("                            <ul class=\"nav nav-pills nav-sidebar flex-column\" data-widget=\"treeview\" role=\"menu\" data-accordion=\"false\">\n");
      out.write("                                ");
 if(session.getAttribute("fullname")!=null){
      out.write("\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"addPatient.jsp\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Add Patients\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"ManagePatients.jsp\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Manage Patients\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                 <li class=\"nav-item has-treeview\">\n");
      out.write("                                    <a href=\"#\" class=\"nav-link\">\n");
      out.write("                                        <i class=\"nav-icon fas fa-users\"></i>\n");
      out.write("                                        <p>\n");
      out.write("                                            Reports\n");
      out.write("                                        </p>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                                ");
}else{
                                    String nextpage="index.jsp";
                                    response.sendRedirect(nextpage);
                                    
                                }
                                
      out.write("\n");
      out.write("                                <li class=\"nav-item has-treeview\">\n");
      out.write("                                <a href=\"logout\" class=\"nav-link\">\n");
      out.write("                                  <i class=\"nav-icon fas fa-lock\"></i>\n");
      out.write("                                  <p>\n");
      out.write("                                   Logout\n");
      out.write("                                  </p>\n");
      out.write("                                </a>\n");
      out.write("                             </li>\n");
      out.write("                                \n");
      out.write("                            </ul>\n");
      out.write("                            \n");
      out.write("                        </nav>\n");
      out.write("            </div>\n");
      out.write("        </aside>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("          \n");
      out.write("  <!-- Content Wrapper. Contains page content -->\n");
      out.write("  <div class=\"content-wrapper\">\n");
      out.write("		 <!-- Main content -->\n");
      out.write("    <section class=\"content\">\n");
      out.write("      <div class=\"container-fluid\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-12\">\n");
      out.write("           \n");
      out.write("<br>\n");
      out.write("            <div class=\"card\">\n");
      out.write("              <div class=\"card-header\">\n");
      out.write("                  <h3 class=\"card-title\" style=\"text-align: center;\">Manage all Patients</h3>\n");
      out.write("              </div>\n");
      out.write("                         <div class=\"card-body\">  \n");
      out.write("                             <div align=\"right\" style=\"margin-bottom: 5px;\">\n");
      out.write("                                 <button type=\"button\" name=\"add\" id=\"add\" class=\"btn btn-success btn-xs\">AddPatient</button>\n");
      out.write("                             </div>\n");
      out.write("                             <table id=\"data_table\" class=\"table table-bordered table-striped\" style=\"width:100%; size: 12px;\">\n");
      out.write("                           <thead>\n");
      out.write("                               <tr>\n");
      out.write("                                  <th>No.</th> \n");
      out.write("                                  <th>Full Name</th> \n");
      out.write("                                  <th>Patient Number</th> \n");
      out.write("                                  <th>Dob</th> \n");
      out.write("                                  <th>National Id</th> \n");
      out.write("                                  <th>Gender</th> \n");
      out.write("                                  <th>Phone</th> \n");
      out.write("                                  <th>Patient Status</th> \n");
      out.write("                                  <th>Marital Status</th> \n");
      out.write("                                  <th></th> \n");
      out.write("                                  \n");
      out.write("                               </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                            </tbody> \n");
      out.write("                        </table>\n");
      out.write("                         </div>  \n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("            <!-- /.card -->\n");
      out.write("          </div>\n");
      out.write("          <!-- /.col -->\n");
      out.write("        </div>\n");
      out.write("        <!-- /.row -->\n");
      out.write("      </div>\n");
      out.write("      <!-- /.container-fluid -->\n");
      out.write("    </section>\n");
      out.write("    <!-- /.content -->\n");
      out.write("    </div>\n");
      out.write("                                            ");

                                                Calendar cal = Calendar.getInstance();  
                                                int year= cal.get(Calendar.YEAR);    
                                            
                                            
      out.write("\n");
      out.write("					<!-- Footer -->\n");
      out.write("                                        <div class=\"footer text-muted\">\n");
      out.write("                                          <p align=\"center\"> &copy <a href=\"#\" title=\"Version 0.1\">Gilbert Patient Reports</a> GILB-REPO, SELF ");
      out.print(year);
      out.write("</p>\n");
      out.write("					</div>\n");
      out.write("					<!-- /footer -->\n");
      out.write("\n");
      out.write("				</div>\n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                         <div id=\"patient_dialog\" title=\"Add Patient\">\n");
      out.write("                                            <form id=\"patient_form\" method=\"post\">\n");
      out.write("                                                <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"firstname\" class=\"form-label\">First Name <b style=\"color:red;\"> *</b>F</label>\n");
      out.write("                                                  <input type=\"text\" class=\"form-control\" id=\"fname\" name=\"fname\" placeholder=\"First Name\"  >\n");
      out.write("                                                  <span id=\"error_first_name\"></span>\n");
      out.write("                                                </div>\n");
      out.write("\n");
      out.write("                                                <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"middlenaame\" class=\"form-label\">Middle Name</label>\n");
      out.write("                                                  <input type=\"text\" class=\"form-control\" id=\"mname\" name=\"mname\" placeholder=\"Middle Name\">\n");
      out.write("                                                </div>\n");
      out.write("                                               <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"lastname\" class=\"form-label\">Last Name<b style=\"color:red;\"> *</b>LN</label>\n");
      out.write("                                                  <input type=\"text\" class=\"form-control\" id=\"lname\" name=\"lname\" placeholder=\"Last Name\"  >\n");
      out.write("                                                  <span id=\"error_last_name\"></span>\n");
      out.write("                                                  \n");
      out.write("                                                </div>\n");
      out.write("                                                 <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"patientnumber\" class=\"form-label\">Patient Number<b style=\"color:red;\"> *</b>PN</label>\n");
      out.write("                                                  <input type=\"text\" class=\"form-control\" id=\"pnumber\" name=\"pnumber\" placeholder=\"Patient Number\"  >\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                  <label for=\"birthday\" class=\"form-label\">DOB<b style=\"color:red;\"> *</b>DOB</label>\n");
      out.write("                                                  <input type=\"text\" class=\"form-control\" id=\"dob\" name=\"dob\"  >\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"maritalstatus\" class=\"form-label\">Marital Status</label>\n");
      out.write("                                                  <select name=\"m_status\" id=\"m_status\">\n");
      out.write("                                                      <option value=\"1\">Single</option>\n");
      out.write("                                                      <option value=\"2\">Married</option>\n");
      out.write("                                                      <option value=\"3\">Widowed</option>\n");
      out.write("                                                      <option value=\"4\">Divorced</option>\n");
      out.write("                                                  </select>\n");
      out.write("                                                </div>\n");
      out.write("\n");
      out.write("                                               <div class=\"mb-3\">\n");
      out.write("                                                   <p>\n");
      out.write("                                                  Patient Status\n");
      out.write("                                                  <input type=\"radio\" id=\"p_status1\" name=\"p_status\" value=\"1\">Alive\n");
      out.write("                                                  <input type=\"radio\" id=\"p_status2\" name=\"p_status\" value=\"2\">is_dead\n");
      out.write("                                                  </p>\n");
      out.write("\n");
      out.write("                                                </div>\n");
      out.write("                                                  <div class=\"mb-3\">\n");
      out.write("                                                      <p>\n");
      out.write("                                                  Gender\n");
      out.write("                                                  <input type=\"radio\" id=\"gender1\" name=\"gender\" value=\"Male\">Male\n");
      out.write("                                                  <input type=\"radio\" id=\"gender2\" name=\"gender\" value=\"Female\">Female\n");
      out.write("                                                  </p>\n");
      out.write("                                                  </div>\n");
      out.write("                                               <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"nationalid\" class=\"form-label\">National Id</label>\n");
      out.write("                                                  <input type=\"text\" id=\"nid\" class=\"form-control\"minlength=\"8\" maxlength=\"10\" id=\"nid\" name=\"nid\" maxlength=\"10\" placeholder=\"National Id\" onkeypress='return numbers(event)'>\n");
      out.write("                                                </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                                <div class=\"mb-3\">\n");
      out.write("                                                  <label for=\"phonenumber\" class=\"form-label\">Phone Number<b style=\"color:red;\"> *</b>P</label>\n");
      out.write("                                                  <input type=\"text\" id=\"phone\" class=\"form-control\"minlength=\"10\" maxlength=\"10\" id=\"phone\" name=\"phone\" maxlength=\"10\" placeholder=\"Phone Number\" onkeypress='return numbers(event)'  >\n");
      out.write("                                                </div>\n");
      out.write("                                                <div class=\"form-group\">\n");
      out.write("                                                    <input type=\"hidden\" name=\"action\" id=\"action\" value=\"addpatients\"/>\n");
      out.write("                                                    <input type=\"hidden\" name=\"hidden_id\" id=\"hidden_id\"/>\n");
      out.write("                                                    <input type=\"submit\" name=\"form_action\" id=\"form_action\" class=\"btn btn-info\"\n");
      out.write("                                                           value=\"Register\"/>\n");
      out.write("                                                    \n");
      out.write("                                                </div>\n");
      out.write("\n");
      out.write("                                                \n");
      out.write("                                            </form>     \n");
      out.write("                                            \n");
      out.write("                                        </div>\n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        <div id=\"action_alert\" title=\"Action\">\n");
      out.write("                                            \n");
      out.write("                                        </div>    \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                        \n");
      out.write("                                                       \n");
      out.write("    </body>\n");
      out.write("    \n");
      out.write("     \n");
      out.write("     <script>\n");
      out.write("   $(document).ready(function() {\n");
      out.write("   load_data();\n");
      out.write("   dialog_task();\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("   \n");
      out.write("}); \n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        function load_data(){\n");
      out.write("            $.ajax({\n");
      out.write("                url:'Load_Patients',\n");
      out.write("                type:'get',\n");
      out.write("                dataType:'json',\n");
      out.write("                      success:function(users){\n");
      out.write("       var dataSet=[];\n");
      out.write("         var data = users.users;\n");
      out.write("         var code = users.code;\n");
      out.write("         var message = users.message;\n");
      out.write("         if(code===1){\n");
      out.write("var pos,id,patientname,pnumber,dob,nid,gender,phone,p_status,m_status;\n");
      out.write("    for (var i=0; i<data.length;i++){\n");
      out.write("        var minSet = [];\n");
      out.write("\n");
      out.write("                pos = data[i].pos;\n");
      out.write("                id = data[i].id;\n");
      out.write("                patientname = data[i].patientname;\n");
      out.write("                pnumber = data[i].pnumber;\n");
      out.write("                dob = data[i].dob;\n");
      out.write("                nid = data[i].nid;\n");
      out.write("                gender = data[i].gender;\n");
      out.write("                phone = data[i].phone;\n");
      out.write("                p_status = data[i].status;\n");
      out.write("                m_status = data[i].mstatus;\n");
      out.write("                \n");
      out.write("                \n");
      out.write("        var resend=\"<button class='btn btn-info btn-raised' onclick='return update(\"+pos+\");' style='padding-top:1px; padding-bottom:1px;'>Update</button>\";\n");
      out.write("//        var deletep=\"<button class='btn btn-info btn-raised' onclick='return update(\"+pos+\");' style='padding-top:1px; padding-bottom:1px;'>Delete</button>\";\n");
      out.write("        var at_=\"<input type='hidden' value='\"+id+\"' id='pos_\"+pos+\"' name='pos_\"+pos+\"'>\";\n");
      out.write("       minSet.push(at_+\"\"+pos);  \n");
      out.write("       minSet.push(patientname);  \n");
      out.write("       minSet.push(pnumber);  \n");
      out.write("       minSet.push(dob);  \n");
      out.write("       minSet.push(nid);  \n");
      out.write("       minSet.push(gender);\n");
      out.write("       minSet.push(phone); \n");
      out.write("       minSet.push(p_status);  \n");
      out.write("       minSet.push(m_status); \n");
      out.write("       minSet.push(resend);\n");
      out.write("//       minSet.push(deletep);\n");
      out.write("       \n");
      out.write("        dataSet.push(minSet);\n");
      out.write("        }\n");
      out.write("       \n");
      out.write("       console.log(dataSet);\n");
      out.write("       \n");
      out.write("        var table = $('#data_table').DataTable();\n");
      out.write("        table.destroy();\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        table = $('#data_table').dataTable({\n");
      out.write("            data: dataSet,\n");
      out.write("            dom: 'Bfltip',\n");
      out.write("        buttons: [\n");
      out.write("           'copy', 'csv', 'excel', 'pdf', 'print'\n");
      out.write("        ],\n");
      out.write("            responsive: true,\n");
      out.write("            className:'',\n");
      out.write("            columnDefs: []\n");
      out.write("            \n");
      out.write("        });\n");
      out.write("        \n");
      out.write("        table.on( 'responsive-resize', function ( e, datatable, columns ) {\n");
      out.write("    var count = columns.reduce( function (a,b) {\n");
      out.write("        return b === false ? a+1 : a;\n");
      out.write("    }, 0 );\n");
      out.write(" \n");
      out.write("    console.log( count +' column(s) are hidden' );\n");
      out.write("} ); \n");
      out.write(" \n");
      out.write("        }\n");
      out.write("        else{\n");
      out.write("//            alert(\"failed :\"+message);\n");
      out.write("          $.jGrowl(message, {\n");
      out.write("                                        position: 'center',\n");
      out.write("                                        header: '<b>Error Loading Users</b>',\n");
      out.write("                                        theme: 'bg-danger'\n");
      out.write("                                   });    \n");
      out.write("            \n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("                \n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("        \n");
      out.write("       \n");
      out.write("  \n");
      out.write("       \n");
      out.write("    </script>\n");
      out.write("    <script>\n");
      out.write("        function dialog_task(){\n");
      out.write("            \n");
      out.write("       $(\"#patient_dialog\").dialog({\n");
      out.write("       autoOpen:false,\n");
      out.write("       width:500,\n");
      out.write("       resizable:true\n");
      out.write("   });\n");
      out.write("   \n");
      out.write("   \n");
      out.write("   $(\"#add\").click(function(){\n");
      out.write("       $(\"#patient_dialog\").attr(\"title\",\"Register Patient\");\n");
      out.write("       $(\"#action\").val(\"addpatients\");\n");
      out.write("       $(\"#form_action\").val(\"Register\");\n");
      out.write("       $(\"#patient_dialog\").dialog(\"open\");\n");
      out.write("       $(\"#patient_dialog\").css(\"background-color\", \"#D3D3D3\");\n");
      out.write("       $(\"#fname\").val(\"\");\n");
      out.write("       $(\"#mname\").val(\"\");\n");
      out.write("       $(\"#lname\").val(\"\");\n");
      out.write("       $(\"#pnumber\").val(\"\");\n");
      out.write("       $(\"#dob\").val(\"\");\n");
      out.write("       $(\"#nid\").val(\"\");\n");
      out.write("           \n");
      out.write("          //var m_status = $('#m_status option[value=1]').attr(\"selected\",\"selected\");\n");
      out.write("       $(\"input[name=p_status]:checked\").val(\"\");\n");
      out.write("       $(\"input[name=gender]:checked\").val(\"\");\n");
      out.write("       $(\"#phone\").val(\"\");\n");
      out.write("   });\n");
      out.write("   $(\"#patient_form\").on(\"submit\",function(event){\n");
      out.write("       event.preventDefault();\n");
      out.write("//       var error_first_name=\"h\";\n");
      out.write("//       if($(\"#fname\").val()==\"\"||$(\"#fname\").val()<2){\n");
      out.write("//           error_first_name=\"Proper Name is required\";\n");
      out.write("//           $(\"#error_first_name\").text(error_first_name);\n");
      out.write("//           $(\"#fname\").css(\"border-color\",\"#cc0000\");\n");
      out.write("//       }\n");
      out.write("//       else{\n");
      out.write("//           error_first_name=\"\";\n");
      out.write("//           $(\"#error_first_name\").text(error_first_name);\n");
      out.write("//           $(\"#fname\").css(\"border-color\",\"\");\n");
      out.write("//       }\n");
      out.write("//       if(error_first_name==\"\"){\n");
      out.write("//           alert(\"missing ................\");\n");
      out.write("//           return true;\n");
      out.write("//       }\n");
      out.write("       //else{\n");
      out.write("           //$(\"#form_action\").attr(\"disabled\",\"disabled\");\n");
      out.write("           var fname = $(\"#fname\").val();\n");
      out.write("           var mname = $(\"#mname\").val();\n");
      out.write("           var lname = $(\"#lname\").val();\n");
      out.write("           var pnumber = $(\"#pnumber\").val();\n");
      out.write("           var dob = $(\"#dob\").val();\n");
      out.write("           var nid = $(\"#nid\").val();\n");
      out.write("           \n");
      out.write("          //var m_status = $('#m_status option[value=1]').attr(\"selected\",\"selected\");\n");
      out.write("          var m_status=$(\"#m_status option:selected\").val();\n");
      out.write("           var p_status = $(\"input[name=p_status]:checked\").val();\n");
      out.write("           var gender = $(\"input[name=gender]:checked\").val();\n");
      out.write("           var phone = $(\"#phone\").val();\n");
      out.write("           var form_data = {\"fname\":fname,\"mname\":mname,\"lname\":lname,\"pnumber\":pnumber,\n");
      out.write("               \"dob\":dob,\"nid\":nid,\"p_status\":p_status,\"gender\":gender,\"phone\":phone,\"m_status\":m_status};\n");
      out.write("           //alert(\"full name \"+fname+\" \"+mname+\" \"+lname+\",\"+\"status\"+p_status+\"\"+gender+\"\"+dob+\"\"+nid+\"\"+pnumber\n");
      out.write("                   //+\"\"+phone+\"\"+m_status);\n");
      out.write("           \n");
      out.write("           //alert(form_data);\n");
      out.write("           $.ajax({\n");
      out.write("               url:'addpatients',\n");
      out.write("               type:\"post\",\n");
      out.write("               data:form_data,\n");
      out.write("               \n");
      out.write("               success:function(){\n");
      out.write("                   $(\"#patient_dialog\").dialog(\"close\");\n");
      out.write("                   //$(\"#action_alert\").dialog(\"open\");\n");
      out.write("                   console.log(form_data);\n");
      out.write("               }\n");
      out.write("           });\n");
      out.write("       //}\n");
      out.write("   });\n");
      out.write("            \n");
      out.write("        }\n");
      out.write("        function update(pos){\n");
      out.write("            var id = $(\"#pos_\"+pos).val();\n");
      out.write("           \n");
      out.write("            var id_data={\"id\":id};\n");
      out.write("            var getdata;\n");
      out.write("            $.ajax({\n");
      out.write("                url:'SelectPatient',\n");
      out.write("                type:\"get\",\n");
      out.write("                data:id_data,\n");
      out.write("                dataType:\"json\",\n");
      out.write("               \n");
      out.write("                success:function(patient){\n");
      out.write("                    console.log(id_data);\n");
      out.write("                    var ddata=patient.xxx;\n");
      out.write("                    var dataset=[];\n");
      out.write("                     var fnamex,mname,lname,pnumber,dob,gender,m_status,p_status,phone,nid,id;\n");
      out.write("//                    for(var i=0;i<ddata.length;i++){\n");
      out.write("//                        var set=[];\n");
      out.write("                        id=ddata.id;\n");
      out.write("                        fnamex=ddata.fname;\n");
      out.write("                        \n");
      out.write("                        mname=ddata.mname;\n");
      out.write("                        lname=ddata.lname;\n");
      out.write("                        pnumber=ddata.pnumber;\n");
      out.write("                        dob=ddata.dob;\n");
      out.write("                        gender=ddata.gender;\n");
      out.write("                        m_status=ddata.m_status;\n");
      out.write("                        p_status=ddata.p_status;\n");
      out.write("                        phone=ddata.phone;\n");
      out.write("                        nid=ddata.nid;\n");
      out.write("                        console.log(fnamex);\n");
      out.write("                        $(\"#patient_dialog\").dialog({\n");
      out.write("                                autoOpen:true,\n");
      out.write("                                width:500,\n");
      out.write("                                resizable:true\n");
      out.write("                            });\n");
      out.write("                            $(\"#patient_dialog\").css(\"background-color\", \"#D3D3D3\");\n");
      out.write("                            $(\"#fname\").val(fnamex);\n");
      out.write("                            $(\"#mname\").val(mname);\n");
      out.write("                            $(\"#lname\").val(lname);\n");
      out.write("                            $(\"#pnumber\").val(pnumber);\n");
      out.write("                            $(\"#dob\").val(dob);\n");
      out.write("                            $(\"#phone\").val(phone);\n");
      out.write("                            $(\"#nid\").val(nid);\n");
      out.write("                            //$(\"input[name=p_status]:check\").val(p_status);\n");
      out.write("                            $(\"input[name=gender][value='\"+gender+\"']\").prop(\"checked\",true);\n");
      out.write("                            $(\"input[name=p_status][value='\"+p_status+\"']\").prop(\"checked\",true);\n");
      out.write("                            $(\"#m_status\").val(m_status).change();\n");
      out.write("                            \n");
      out.write("                            $(\"#dob\").datepicker({\n");
      out.write("                                maxDate:0\n");
      out.write("                                \n");
      out.write("                            });\n");
      out.write("                        \n");
      out.write("                        \n");
      out.write("                       \n");
      out.write("                        \n");
      out.write("//                    }\n");
      out.write("                    \n");
      out.write("                    console.log(m_status);\n");
      out.write("                    console.log(p_status);\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    </script>\n");
      out.write("   \n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
